@echo off
setlocal EnableDelayedExpansion

:: ── Version — bump this for every release. Must match MyAppVersion in
::    MFlow.iss, since the installer builds the R2 download URL from it.
set MFLOW_VERSION=2.6.0
set MFLOW_ARCH=x64
set MFLOW_TAG=v%MFLOW_VERSION%
set MFLOW_ZIP=MFlow-%MFLOW_TAG%-%MFLOW_ARCH%-standalone.zip

title Build MFlow %MFLOW_TAG%

echo.
echo  ============================================
echo   MFlow %MFLOW_TAG% ^| Build with PyInstaller
echo  ============================================
echo.
:: ── 0. Verify we're in the right folder ────────────────────────────────────
:: This .bat lives in packaging/, one level below the project root
:: (where main.py, MFlow.ico, requirements.txt, core/, ui/, etc. are).
if not exist "..\main.py" (
    echo [ERROR] ..\main.py not found.
    echo         Run this .bat from packaging\ inside the MFlow project
    echo         ^(main.py should be one level up^).
    pause & exit /b 1
)
if not exist "MFlow.spec" (
    echo [ERROR] MFlow.spec not found in this folder.
    pause & exit /b 1
)
if not exist "..\MFlow.ico" (
    echo [ERROR] ..\MFlow.ico not found.
    echo         It should be in the project root, next to main.py.
    pause & exit /b 1
)
if not exist "..\requirements.txt" (
    echo [ERROR] ..\requirements.txt not found.
    pause & exit /b 1
)

:: ── 1. Check Python ─────────────────────────────────────────────────────────
echo [1/6] Checking Python...
python --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python not found in PATH.
    echo         Install Python 3.10+ and check "Add to PATH" during setup.
    pause & exit /b 1
)
for /f "tokens=2 delims= " %%v in ('python --version 2^>^&1') do set PYVER=%%v
echo        Python !PYVER! found.

:: ── 2. Install / update dependencies ────────────────────────────────────────
echo.
echo [2/6] Installing dependencies (pip)...
python -m pip install --quiet --upgrade pip
if errorlevel 1 (
    echo [ERROR] Failed to upgrade pip.
    pause & exit /b 1
)
python -m pip install --quiet -r ..\requirements.txt
if errorlevel 1 (
    echo [ERROR] Failed to install dependencies from requirements.txt.
    echo         ^(PySide6^) — PyInstaller needs it importable to resolve
    echo         hiddenimports correctly.
    pause & exit /b 1
)
python -m pip install --quiet pyinstaller
if errorlevel 1 (
    echo [ERROR] Failed to install PyInstaller.
    pause & exit /b 1
)
echo        Dependencies OK.

:: ── 3. Clean previous build ──────────────────────────────────────────────────
echo.
echo [3/6] Cleaning previous build...
if exist "dist\MFlow" (
    rmdir /s /q "dist\MFlow"
    echo        dist\MFlow removed.
)
if exist "build\MFlow" (
    rmdir /s /q "build\MFlow"
    echo        build\MFlow removed.
)
if exist "release\%MFLOW_ZIP%" (
    del /q "release\%MFLOW_ZIP%"
    echo        previous zip removed.
)

:: ── 4. Build with PyInstaller ────────────────────────────────────────────────
echo.
echo [4/6] Building with PyInstaller...
echo.

python -m PyInstaller MFlow.spec --clean --noconfirm
if errorlevel 1 (
    echo.
    echo [ERROR] PyInstaller finished with errors.
    echo         Check the output above. Common causes:
    echo           - PySide6 not installed: pip install PySide6
    echo           - MFlow.spec missing or malformed
    pause & exit /b 1
)

if not exist "dist\MFlow\MFlow.exe" (
    echo [ERROR] Build finished but dist\MFlow\MFlow.exe was not found.
    pause & exit /b 1
)

:: ── 5. Package dist\MFlow into a versioned .zip for R2 ──────────────────────
echo.
echo [5/6] Packaging dist\MFlow -^> release\%MFLOW_ZIP%
if not exist "release" mkdir "release"

powershell -NoProfile -Command ^
    "Compress-Archive -Path 'dist\MFlow\*' -DestinationPath 'release\%MFLOW_ZIP%' -Force"
if errorlevel 1 (
    echo [ERROR] Failed to compress dist\MFlow.
    pause & exit /b 1
)

:: ── 6. Generate version.iss (size + SHA-256 for Inno Setup) ─────────────────
echo.
echo [6/6] Generating version.iss...

for /f "usebackq delims=" %%s in (`powershell -NoProfile -Command ^
    "(Get-ChildItem -Recurse -File 'dist\MFlow').Length | Measure-Object -Sum | Select-Object -ExpandProperty Sum"`) do set STANDALONE_SIZE=%%s

if "%STANDALONE_SIZE%"=="" (
    echo [ERROR] Could not calculate the size of dist\MFlow.
    pause & exit /b 1
)

for /f "usebackq delims=" %%h in (`powershell -NoProfile -Command ^
    "(Get-FileHash -Algorithm SHA256 -Path 'release\%MFLOW_ZIP%').Hash.ToLower()"`) do set STANDALONE_SHA256=%%h

if "%STANDALONE_SHA256%"=="" (
    echo [ERROR] Could not calculate the SHA-256 of release\%MFLOW_ZIP%.
    pause & exit /b 1
)

> version.iss (
    echo ; Auto-generated by build_mflow.bat — do NOT edit by hand.
    echo ; Used by MFlow.iss for the ExternalSize/Hash of download+extractarchive.
    echo #define StandaloneExternalSize %STANDALONE_SIZE%
    echo #define StandaloneSHA256 "%STANDALONE_SHA256%"
)
echo        version.iss generated ^(%STANDALONE_SIZE% bytes, sha256 %STANDALONE_SHA256%^).

:: ── Publish this same hash in this version's changelog/release notes ───────
echo.
echo  ============================================
echo   SHA-256 of release\%MFLOW_ZIP%:
echo   %STANDALONE_SHA256%
echo.
echo   Copy it into this version's changelog/release notes.
echo  ============================================

:: ── Result ───────────────────────────────────────────────────────────────────
echo.
echo  ============================================
echo   Build succeeded.
echo.
echo   Executable folder: dist\MFlow\MFlow.exe
echo   Zip for R2:         release\%MFLOW_ZIP%
echo   version.iss:        ready for MFlow.iss
echo.
echo   Next steps:
echo     1. Upload release\%MFLOW_ZIP% to R2
echo        (see upload_to_r2.bat)
echo     2. Confirm MFLOW_VERSION and MFLOW_ARCH above match
echo        MyAppVersion and MyAppArch in MFlow.iss
echo     3. Publish the SHA-256 above in this version's changelog
echo     4. Open MFlow.iss with Inno Setup 6 (6.4+) and compile the installer
echo     5. Run sign_release.bat to produce SHA256SUMS.txt + GPG signature
echo  ============================================
echo.
pause
