; MFlow — Inno Setup 6 (requires 6.4 or newer; get the latest from
; https://jrsoftware.org/isinfo.php — the "extractarchive" [Files] flag and
; the "full" ArchiveExtraction method used below were added in 6.4/6.5)
;
; Lives in packaging/, alongside MFlow.spec and the two .bat files — one
; level below the project root (main.py, core/, ui/, etc.), hence the "..\"
; prefixes throughout [Files]/SetupIconFile/LicenseFile below.
;
; Compile this AFTER build_mflow.bat has finished and the standalone .zip has
; been uploaded to R2 (see upload_to_r2.bat) — the compiler needs
; version.iss (generated by build_mflow.bat into this same packaging/ folder)
; to exist alongside this file.
;
; ── Why no third-party download plugin ──────────────────────────────────────
; Older Inno Setup installers commonly used a third-party DLL (Inno Download
; Plugin / idp.dll) to download files with a progress bar. Since Inno Setup
; 6.4/6.5, this is no longer necessary: the [Files] section supports
; `Flags: download extractarchive` natively — Setup downloads AND extracts
; the archive itself, with its own built-in progress UI, no external DLL,
; maintained directly by Inno Setup's own author. That's what this script
; uses below.
;
; ── What changed vs the old embedded-exe installer ───────────────────────────
; - The standalone build (dist\MFlow\* from PyInstaller) is no longer bundled
;   directly. It's downloaded from R2 as a single .zip and extracted straight
;   to {app} by Setup itself, ONLY if the "standalone" task is checked.
; - The Resolve bridge source (main.py, core/, ui/, presets/, etc.) is still
;   embedded exactly like before — it's small (plain .py/.json/.html) and
;   Resolve's embedded Python can't import from a frozen exe anyway. It is
;   only installed if "studio" or "free" is checked; someone who only wants
;   the standalone app never gets this copied into %appdata%\MFlow.
; - Three independent task checkboxes: standalone / studio / free.
; - If the standalone download fails, Setup shows its normal file error
;   dialog (Abort/Retry/Ignore). Choosing "Ignore" skips just that file and
;   continues installing everything else selected (Resolve integration is
;   embedded, so it never depends on this download at all).

#define MyAppVersion "2.6.0"
#define MyAppArch "x64"
; ReleaseTag is the display/filename form ("v2.6.0") — the bare MyAppVersion
; (no "v") is what stays in AppVersion below, since that's what Windows'
; internal file/product versioning expects in plain X.Y.Z(.W) form.
#define ReleaseTag "v" + MyAppVersion
#define R2BaseURL "https://pub-2c103f7a5e7446659633c0a34c70d6ed.r2.dev"
#define StandaloneZipName "MFlow-" + ReleaseTag + "-" + MyAppArch + "-standalone.zip"
#define StandaloneZipURL R2BaseURL + "/" + StandaloneZipName

; Generated by build_mflow.bat right after zipping dist\MFlow — contains:
;   #define StandaloneExternalSize <bytes>
; (the total uncompressed size of the standalone build, required by Inno
; Setup when combining the download and extractarchive flags). Must exist
; before compiling; run build_mflow.bat first.
#include "version.iss"

[Setup]
AppName=MFlow
AppVersion={#MyAppVersion}
AppPublisher=MMarket
AppPublisherURL=https://codeberg.org/MaaruAx/MFlow
AppSupportURL=https://codeberg.org/MaaruAx/MFlow
DefaultDirName={autopf}\MFlow
DefaultGroupName=MFlow
OutputBaseFilename=MFlow-{#ReleaseTag}-{#MyAppArch}-Setup
OutputDir=installer
; Explicit 64-bit declaration — matches the "-x64" in the filename and
; ensures {autopf}/{app} resolve to the real 64-bit Program Files, not the
; x86 one, on 64-bit Windows.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
Compression=lzma2/ultra64
SolidCompression=yes
CompressionThreads=auto
WizardStyle=modern
MinVersion=10.0
PrivilegesRequired=admin
; "full" is required to extract .zip (the default "basic" only handles .7z).
; Adds ~465 KB to the installer — negligible next to what it saves in
; not having to bundle the standalone build itself.
ArchiveExtraction=full

; Close MFlow if it is running before install/update
CloseApplications=yes
CloseApplicationsFilter=MFlow.exe
RestartIfNeededByRun=no

; Icons — one level up since this .iss now lives in packaging/
SetupIconFile=..\MFlow.ico
UninstallDisplayName=MFlow

; License dialog
LicenseFile=..\LICENSE

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
; Independent checkboxes — any combination is valid. A warning is shown if
; the user unchecks all three (see NextButtonClick below).
Name: "standalone"; Description: "Install standalone application (downloads MFlow.exe from the release server)"; GroupDescription: "Components:"
Name: "studio";     Description: "DaVinci Resolve Studio integration (Workspace > Scripts > MFlow, any page)"; GroupDescription: "Components:"
Name: "free";       Description: "DaVinci Resolve Free integration (Fusion page > Scripts > Comp > MFlow_Free)"; GroupDescription: "Components:"
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional options:"

[Dirs]
; User data dir — never removed on uninstall (the [Code] handler asks the user)
Name: "{userappdata}\MFlow\themes";   Flags: uninsneveruninstall
Name: "{userappdata}\MFlow\presets";  Flags: uninsneveruninstall
Name: "{userappdata}\MFlow\language"; Flags: uninsneveruninstall

[Files]
; ── Standalone build → {app} ─────────────────────────────────────────────
; Downloaded from R2 and extracted directly by Setup — no [Code] needed.
; DestName's .zip extension is how Setup knows which archive format to use.
Source: "{#StandaloneZipURL}"; DestDir: "{app}"; DestName: "{#StandaloneZipName}"; \
    ExternalSize: {#StandaloneExternalSize}; Tasks: standalone; \
    Flags: external download extractarchive ignoreversion recursesubdirs createallsubdirs

; ── Resolve bridge source → %APPDATA%\MFlow ─────────────────────────────────
; Only installed if the Studio or Free integration is selected. Never touches
; the standalone install path — the standalone .exe is fully self-contained
; (PyInstaller onedir bundle) and does not need any of this at runtime.
Source: "..\main.py";              DestDir: "{userappdata}\MFlow"; Flags: ignoreversion; Tasks: studio or free
Source: "..\bridge.py";            DestDir: "{userappdata}\MFlow"; Flags: ignoreversion; Tasks: studio or free
Source: "..\MFlow_bridge.py";      DestDir: "{userappdata}\MFlow"; Flags: ignoreversion; Tasks: studio or free
Source: "..\MFlow_Free.py";        DestDir: "{userappdata}\MFlow"; Flags: ignoreversion; Tasks: studio or free
Source: "..\MFlow.lua";            DestDir: "{userappdata}\MFlow"; Flags: ignoreversion; Tasks: studio or free
Source: "..\MFlow.ico";            DestDir: "{userappdata}\MFlow"; Flags: ignoreversion; Tasks: studio or free

Source: "..\core\*.py";            DestDir: "{userappdata}\MFlow\core";     Flags: ignoreversion; Tasks: studio or free
Source: "..\ui\backend.py";        DestDir: "{userappdata}\MFlow\ui";       Flags: ignoreversion; Tasks: studio or free
Source: "..\ui\app.html";          DestDir: "{userappdata}\MFlow\ui";       Flags: ignoreversion; Tasks: studio or free
Source: "..\ui\dock.html";         DestDir: "{userappdata}\MFlow\ui";       Flags: ignoreversion; Tasks: studio or free
Source: "..\ui\Monaspace_Neon_Var.woff2"; DestDir: "{userappdata}\MFlow\ui"; Flags: ignoreversion; Tasks: studio or free

Source: "..\presets\*.json";       DestDir: "{userappdata}\MFlow\presets";  Flags: ignoreversion; Tasks: studio or free
Source: "..\language\*.json";      DestDir: "{userappdata}\MFlow\language"; Flags: ignoreversion; Tasks: studio or free
; Themes: onlyifdoesntexist — never overwrite user customizations
Source: "..\themes\*.json";        DestDir: "{userappdata}\MFlow\themes";   Flags: onlyifdoesntexist; Tasks: studio or free

[Icons]
Name: "{group}\MFlow";       Filename: "{app}\MFlow.exe"; Tasks: standalone
Name: "{userdesktop}\MFlow"; Filename: "{app}\MFlow.exe"; Tasks: standalone and desktopicon

[Run]
Filename: "{app}\MFlow.exe"; Description: "Launch MFlow"; Flags: nowait postinstall skipifsilent; Tasks: standalone

[UninstallDelete]
; Remove the entire installation folder on uninstall
; (including files not originally placed by the installer)
Type: filesandordirs; Name: "{app}"

[Code]

// Appends the exact file (with version) that will be downloaded to the
// Ready page's summary, so the user sees it before clicking Install.
function UpdateReadyMemo(Space, NewLine, MemoUserInfoInfo, MemoDirInfo, MemoTypeInfo,
  MemoComponentsInfo, MemoGroupInfo, MemoTasksInfo: String): String;
begin
  Result := MemoDirInfo + NewLine + NewLine + MemoTasksInfo;
  if IsTaskSelected('standalone') then
    Result := Result + NewLine + NewLine + 'Will download:' + NewLine +
      Space + '{#StandaloneZipName}' + NewLine +
      Space + 'from {#R2BaseURL}';
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  // Gentle nudge if the user unchecked everything — not a hard block, since
  // they may legitimately just want to re-run one specific step later.
  if CurPageID = wpSelectTasks then
  begin
    if (not IsTaskSelected('standalone')) and (not IsTaskSelected('studio')) and (not IsTaskSelected('free')) then
    begin
      if MsgBox('No components are selected, so this installer will not install anything.' + #13#10 +
                'Continue anyway?', mbConfirmation, MB_YESNO) = IDNO then
        Result := False;
    end;
  end;
end;

// After install: write mflow_path.txt to Resolve's Scripts folders and copy bridge files.
// Resolve's embedded Python reads mflow_path.txt to locate MFlow's source.
procedure CurStepChanged(CurStep: TSetupStep);
var
  DataDir, UtilityDir, CompDir: String;
begin
  if CurStep = ssPostInstall then
  begin
    DataDir := ExpandConstant('{userappdata}\MFlow');

    // Studio bridge (Utility — any page, launches MFlow.lua → python main.py)
    if IsTaskSelected('studio') then
    begin
      UtilityDir := ExpandConstant('{userappdata}\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Utility');
      if DirExists(UtilityDir) then
      begin
        FileCopy(DataDir + '\MFlow.lua',       UtilityDir + '\MFlow.lua',       False);
        SaveStringToFile(UtilityDir + '\mflow_path.txt', DataDir, False);
      end;
    end;

    // Free bridge (Comp — Fusion page only, Resolve injects app directly)
    if IsTaskSelected('free') then
    begin
      CompDir := ExpandConstant('{userappdata}\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Comp');
      if DirExists(CompDir) then
      begin
        FileCopy(DataDir + '\MFlow_Free.py',   CompDir + '\MFlow_Free.py',      False);
        SaveStringToFile(CompDir + '\mflow_path.txt', DataDir, False);
      end;
    end;
  end;
end;

// After uninstall, ask the user whether to also delete their saved data
// (presets, themes, settings). The install folder is already removed by [UninstallDelete].
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    // Remove bridge files from Resolve's Scripts folders
    DeleteFile(ExpandConstant('{userappdata}\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Utility\MFlow.lua'));
    DeleteFile(ExpandConstant('{userappdata}\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Utility\mflow_path.txt'));
    DeleteFile(ExpandConstant('{userappdata}\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Comp\MFlow_Free.py'));
    DeleteFile(ExpandConstant('{userappdata}\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\Comp\mflow_path.txt'));

    // Ask whether to delete user data
    DataDir := ExpandConstant('{userappdata}\MFlow');
    if DirExists(DataDir) then
    begin
      if MsgBox(
        'MFlow found saved user data at:' + #13#10 +
        DataDir + #13#10 + #13#10 +
        'This folder contains your presets, themes and settings.' + #13#10 +
        'Do you want to delete it as well?',
        mbConfirmation, MB_YESNO) = IDYES then
      begin
        DelTree(DataDir, True, True, True);
      end;
    end;
  end;
end;
